const __R=require('path').resolve(__dirname,'../..'), __T=process.env.UPE_TRABALHO||__R+'/tools/.trabalho';
const {chromium}=require('playwright');const path=require('path'),fs=require('fs');const O=process.argv[2]||__T;const R=__R+'/site/apps/';
const FS=__dirname+'/node_modules/@fontsource/';
const CSS=['figtree:400','figtree:500','figtree:600','figtree:700','barlow-condensed:600','barlow-condensed:700','lato:400','lato:700','lato:900'].map(x=>{const [f,w]=x.split(':');const fam={figtree:'Figtree','barlow-condensed':'Barlow Condensed',lato:'Lato'}[f];return `@font-face{font-family:'${fam}';font-weight:${w};src:url(http://srv.test/__f/${f}/files/${f}-latin-${w}-normal.woff2)}`}).join('\n');
module.exports.rotas=async(ctx,app)=>{
 await ctx.route(/fonts\.googleapis\.com/,r=>r.fulfill({body:CSS,contentType:'text/css'}));
 await ctx.route(/cdnjs\.cloudflare\.com.*qrcode/,r=>r.fulfill({path:__dirname+'/node_modules/qrcodejs2/qrcode.min.js',contentType:'application/javascript'}));
 await ctx.route(/^https?:\/\/(?!srv\.test|fonts\.googleapis|cdnjs)/,r=>r.abort());
 await ctx.route(/^http:\/\/srv\.test\//,r=>{let u=decodeURIComponent(new URL(r.request().url()).pathname);if(u.startsWith('/__f/')){let fp=u.startsWith('/__f/lato/')?__dirname+'/../conteudo/node_modules/@fontsource/lato/files/'+u.split('/').pop():FS+u.slice(5);return fs.existsSync(fp)?r.fulfill({path:fp}):r.fulfill({status:404,body:''})}let f=path.join(R+app,u);if(u.endsWith('/'))f+='index.html';if(!fs.existsSync(f))f=path.join(R+app,{sistemas:'agenda.html',lp:'pagina.html'}[app]||'index.html');
  const ct={'.html':'text/html','.js':'application/javascript','.json':'application/json','.png':'image/png','.jpg':'image/jpeg','.woff2':'font/woff2','.css':'text/css'}[path.extname(f)]||'text/plain';r.fulfill({path:f,contentType:ct})});};
if(require.main===module)(async()=>{const b=await chromium.launch();const ctx=await b.newContext({viewport:{width:1440,height:900}});await module.exports.rotas(ctx,'servicos');
 const p=await ctx.newPage();const errs=[];p.on('pageerror',e=>errs.push('PAGE '+e.message));p.on('console',m=>{if(m.type()==='error')errs.push('CONS '+m.text().slice(0,200))});p.on('dialog',d=>d.accept());
 await p.goto('http://srv.test/?demo=1');await p.waitForSelector('[data-demo]');await p.click('[data-demo="cliente"]');await p.waitForSelector('#nav button',{timeout:20000});await p.waitForTimeout(1500);
 const vis=[['inicio','#/inicio'],['paginas','#/paginas'],['editar','#/pagina/studio-bem-estar/editar'],['codigo','#/pagina/studio-bem-estar/codigo'],['config','#/pagina/studio-bem-estar/config'],['versoes','#/pagina/studio-bem-estar/versoes'],['analise','#/analise'],['leads','#/leads'],['dominios','#/dominios'],['agenda','#/agenda'],['ag-serv','#/agenda/servicos'],['ag-hor','#/agenda/horarios'],['ag-pag','#/agenda/pagina'],['ag-prof','#/agenda/profissionais'],['dash','#/dash'],['dash-lp','#/dash/demo-lp'],['conta','#/conta'],['chamados','#/chamados']];
 for(const [n,h] of vis){await p.evaluate(h=>location.hash=h,h);await p.waitForTimeout(1200);const t=await p.textContent('#main');if(/Não foi possível carregar/.test(t))errs.push('VIEW '+n+': '+t.slice(0,200));await p.screenshot({path:`${O}/c-${n}.png`,fullPage:n!=='editar'});}
 await p.click('#btnSair');await p.waitForSelector('[data-demo]');await p.click('[data-demo="admin"]');await p.waitForSelector('#nav button');await p.waitForTimeout(1000);
 for(const n of ['clientes','cobrancas','planos','interessados','dominios','paginas','chamados','config','erros']){await p.evaluate(h=>location.hash=h,'#/adm/'+n);await p.waitForTimeout(1200);const t=await p.textContent('#main');if(/Não foi possível carregar/.test(t))errs.push('ADM '+n+': '+t.slice(0,200));await p.screenshot({path:`${O}/a-${n}.png`,fullPage:true});}
 console.log('ERROS',JSON.stringify(errs,null,1));await b.close();process.exit(errs.length?1:0)})();
