import json
K=["historia","contexto","narrativa","climax","questionamento","solucao","fundamentacao","cta"]
L={"historia":"A história","contexto":"Contexto","narrativa":"Narrativa","climax":"Clímax","questionamento":"A pergunta","solucao":"A solução","fundamentacao":"Por que funciona","cta":"Próximo passo"}
S=[
("yt-01-filme-upe","Da identidade à venda",[
 ("A dona de um café do bairro tinha um produto ótimo e uma marca que ninguém lembrava.","redesign.jpg"),
 ("Logo antigo, cores diferentes em cada lugar e pedidos anotados no caderno.","redesign.jpg"),
 ("Ela começou pela identidade: logotipo, paleta, tipografia e um manual.","brand.jpg"),
 ("Com a marca pronta, o movimento cresceu. E os pedidos começaram a se perder.","erp-pedidos.jpg"),
 ("Como manter a marca forte sem perder nenhuma venda?","erp-painel.jpg"),
 ("Loja online, PDV e pedidos num só painel. E a marca na TV do bairro.","tv-tela.jpg"),
 ("Marca consistente gera reconhecimento. Processo organizado gera recompra.","brand.jpg"),
 ("Fale com a Upe e leve a sua marca da identidade à venda.","filme-h.jpg")]),
("yt-02-upe-erp","Três lugares de venda, nenhum com todos os pedidos",[
 ("Uma doceria vendia pelo Instagram, pelo WhatsApp e no balcão.","erp-pedidos.jpg"),
 ("Três lugares de venda e nenhum com todos os pedidos.","erp-pedidos.jpg"),
 ("PIX conferido por print, estoque no papel e o cliente perguntando: cadê meu pedido?","erp-painel.jpg"),
 ("Na semana mais movimentada, dois pedidos iguais saíram para o mesmo endereço.","erp-pedidos.jpg"),
 ("E se tudo chegasse organizado, com pagamento e rastreio?","erp-painel.jpg"),
 ("Upe ERP: loja virtual, PDV, PIX com QR Code e gestão de pedidos.","erp-pdv.jpg"),
 ("Cada venda baixa o estoque. Cada pedido tem status e link de acompanhamento.","erp-pdv.jpg"),
 ("Teste 14 dias grátis em upe-erp.web.app.","erp-painel.jpg")]),
("yt-03-upe-tv","A tela que todo mundo olha",[
 ("Uma padaria queria ser lembrada por quem passa no bairro.","tv-tela.jpg"),
 ("Panfleto vai para o lixo. Anúncio online some no feed.","tv-tela.jpg"),
 ("Enquanto isso, na fila do café ao lado, todo mundo olhava para a TV.","tv-tela.jpg"),
 ("E ninguém estava falando com essas pessoas.","tv-qr.jpg"),
 ("E se a sua marca estivesse nessa tela, com um jeito de chamar você na hora?","tv-qr.jpg"),
 ("Upe TV: campanha nas TVs parceiras, com QR code para o seu WhatsApp.","tv-tela.jpg"),
 ("Público local todos os dias, e cada leitura do QR aparece no relatório.","tv-portal.jpg"),
 ("Anuncie ou seja um ponto parceiro: upe-tv.web.app.","tv-tela.jpg")]),
("yt-04-branding-x-logo","Eu só queria um logo novo",[
 ("Um cliente chegou pedindo: quero um logo novo.","redesign.jpg"),
 ("O logo era bom. O problema era todo o resto.","redesign.jpg"),
 ("Cada post de uma cor, a fachada diferente do Instagram, a embalagem sem padrão.","brand.jpg"),
 ("Um logo novo, sozinho, não resolveria nada.","redesign.jpg"),
 ("Então, o que faz uma marca ser reconhecida?","brand.jpg"),
 ("Um sistema: logo, paleta, tipografia, ícones, padrões e manual.","brand.jpg"),
 ("Repetição consistente é o que cria memória de marca.","brand.jpg"),
 ("Assista ao vídeo completo e fale com a Upe sobre a sua marca.","filme-h.jpg")]),
("yt-05-tutorial-erp-1","Sua loja no ar em menos de uma hora",[
 ("Abrir uma loja online parecia coisa de empresa grande.","erp-painel.jpg"),
 ("Site caro, sistema complicado e mensalidade alta.","erp-painel.jpg"),
 ("Neste tutorial: do primeiro acesso à primeira venda, em 7 passos.","erp-painel.jpg"),
 ("Passo 3, ativar o PIX: é aqui que a loja começa a vender de verdade.","erp-pdv.jpg"),
 ("Quanto tempo leva para a loja ficar pronta?","erp-painel.jpg"),
 ("Menos de uma hora, seguindo o roteiro da tela inicial.","erp-painel.jpg"),
 ("Dados, marca, PIX, produto, banner, venda e assinatura: tudo guiado.","erp-pedidos.jpg"),
 ("Assista ao passo a passo e teste 14 dias grátis.","erp-painel.jpg")]),
("yt-06-rebranding-5-sinais","A marca que tinha vergonha de aparecer",[
 ("Um café com 20 anos de história escondia o próprio logo.","redesign.jpg"),
 ("O nome não lia no celular e cada cardápio tinha uma cor.","redesign.jpg"),
 ("Listamos os sinais: leitura, consistência, cores, época e orgulho.","brand.jpg"),
 ("O dono tinha vergonha de entregar o próprio cartão.","redesign.jpg"),
 ("Dá para mudar sem perder quem já conhece a marca?","redesign.jpg"),
 ("Redesign: mantém a essência e corrige o que atrapalha.","redesign.jpg"),
 ("O cliente reconhece a evolução quando os ativos certos ficam.","brand.jpg"),
 ("Marcou 2 sinais ou mais? Fale com a Upe.","filme-h.jpg")]),
("yt-07-tutorial-erp-black-friday","A Black Friday que vendeu demais",[
 ("Na última Black Friday, a loja vendeu mais do que conseguia entregar.","erp-pdv.jpg"),
 ("Estoque errado, cupom que não funcionou e frete sem regra.","erp-painel.jpg"),
 ("Este ano, o checklist começa 30 dias antes.","erp-painel.jpg"),
 ("27 de novembro chega rápido. Quem prepara antes vende sem susto.","erp-pedidos.jpg"),
 ("O que configurar primeiro?","erp-painel.jpg"),
 ("Estoque, cupons, frete grátis, banners e newsletter no Upe ERP.","erp-pdv.jpg"),
 ("Promoção organizada vende mais e gera menos reclamação.","erp-pedidos.jpg"),
 ("Assista e deixe a sua loja pronta para a Black Friday.","erp-painel.jpg")]),
("yt-08-upe-tv-na-pratica","Viu na TV, pediu pelo celular",[
 ("Uma hamburgueria (exemplo) apareceu na TV do café ao lado.","tv-tela.jpg"),
 ("O cliente esperava o café e viu o cardápio na tela.","tv-tela.jpg"),
 ("Apontou a câmera para o QR e abriu o cardápio no celular.","tv-qr.jpg"),
 ("Em minutos, o pedido chegou pronto no WhatsApp.","tv-qr.jpg"),
 ("Dá para saber de qual TV veio o pedido?","tv-portal.jpg"),
 ("Sim: o pedido mostra em qual tela o cliente viu a marca.","tv-qr.jpg"),
 ("Do olhar à conversa, com cada leitura medida no portal.","tv-portal.jpg"),
 ("Anuncie no Upe TV: upe-tv.web.app.","tv-tela.jpg")]),
("yt-09-manual-de-marca","A marca que se desfez aos poucos",[
 ("A marca nova ficou linda no lançamento.","brand.jpg"),
 ("Seis meses depois, cada fornecedor usava uma versão diferente.","redesign.jpg"),
 ("Logo esticado, cor trocada e fonte improvisada.","redesign.jpg"),
 ("A marca começou a se desfazer aos poucos.","redesign.jpg"),
 ("Como proteger a identidade no dia a dia?","brand.jpg"),
 ("O manual da marca: versões, cores, tipografia e regras de uso.","brand.jpg"),
 ("Quem aplica a marca precisa de regras claras, não de adivinhação.","brand.jpg"),
 ("Assista e veja o que tem dentro de um manual.","filme-h.jpg")]),
("yt-10-tutorial-erp-pdv","A fila do balcão",[
 ("Fila no balcão e o cliente perguntando qual é a chave PIX.","erp-pdv.jpg"),
 ("Digitar o valor, conferir o print, anotar no caderno.","erp-pdv.jpg"),
 ("Com o PDV, o produto entra pelo código e o total aparece na hora.","erp-pdv.jpg"),
 ("O QR Code do PIX sai com o valor certo, sem digitar nada.","erp-pdv.jpg"),
 ("E o estoque da loja online?","erp-painel.jpg"),
 ("Baixa sozinho: balcão e internet usam o mesmo cadastro.","erp-painel.jpg"),
 ("Menos erro, fila mais rápida e relatório no fim do dia.","erp-pedidos.jpg"),
 ("Teste o Upe ERP 14 dias grátis.","erp-painel.jpg")]),
("yt-11-retrospectiva","O ano em que a Upe decolou",[
 ("2026 foi o ano em que a Upe Criativo decolou.","filme-h.jpg"),
 ("Começou com branding e redesign para negócios locais.","brand.jpg"),
 ("Vieram o Upe ERP, para vender, e o Upe TV, para aparecer.","erp-painel.jpg"),
 ("Marcas novas, lojas no ar e telas pelo bairro.","tv-tela.jpg"),
 ("O que vem em 2027?","filme-h.jpg"),
 ("Mais marcas, mais telas e o portal do cliente para acompanhar tudo.","brand.jpg"),
 ("Da identidade à venda, com uma marca forte no centro.","brand.jpg"),
 ("Obrigado por acompanhar! Siga @upecriativo.","filme-h.jpg")]),
]
out=[dict(id=i,titulo=t,beats=[dict(k=K[n],rotulo=L[K[n]],texto=b[0],img=b[1]) for n,b in enumerate(bs)]) for i,t,bs in S]
json.dump(out,open(__import__('os').path.join(__import__('os').path.dirname(__file__),'yt_stories.json'),'w'),ensure_ascii=False,indent=1)
print(len(out))
