/* Cronograma de conteúdo @planotecidos — 12/10 a 22/11/2026 (6 semanas).
   Cada item alimenta: a página do cronograma (index.html), o estúdio de artes (studio.html)
   e o render (render.js). Fotos de produto: recortes do próprio Instagram da marca (assets/fotos). */
window.SEMANAS=[
 {n:1,ini:'2026-10-12',tema:'Nova fase da marca',meta:'Apresentar o redesign e explicar o L-rolo.'},
 {n:2,ini:'2026-10-19',tema:'Conheça os tecidos',meta:'Educar e mostrar o catálogo real.'},
 {n:3,ini:'2026-10-26',tema:'Halloween & fantasias',meta:'Aproveitar a demanda sazonal por fantasias.'},
 {n:4,ini:'2026-11-02',tema:'Como comprar',meta:'Tirar atritos: metragem, WhatsApp e Shopee.'},
 {n:5,ini:'2026-11-09',tema:'Fim de ano começa no ateliê',meta:'Mesa posta, Natal e encomendas.'},
 {n:6,ini:'2026-11-16',tema:'Aquecimento Black Friday',meta:'Lista de desejos e lembretes para a Black Friday (27/11).'}
];
window.PILARES={
 marca:{nome:'Marca',cor:'#24402A',desc:'Redesign, manifesto, quem somos.'},
 produto:{nome:'Produto',cor:'#4E8C34',desc:'Tecidos reais, cores, texturas e usos.'},
 educa:{nome:'Educação',cor:'#86BC5F',desc:'Dicas de costura, metragem e escolha de tecido.'},
 prova:{nome:'Prova social',cor:'#D6CAB4',desc:'Nota 5 na Shopee, clientes e projetos prontos.'},
 bastidor:{nome:'Bastidores',cor:'#9B9486',desc:'Corte, embalagem e rotina da loja.'},
 oferta:{nome:'Oferta',cor:'#2B2B29',desc:'Datas sazonais e chamadas para compra.'}
};
const WA='WhatsApp (11) 99383-9570';
window.POSTS=[
/* ---------------- SEMANA 1 ---------------- */
{id:'s1-01',date:'2026-10-12',hora:'19h',fmt:'carrossel',pilar:'marca',titulo:'A Plano tem cara nova',
 objetivo:'Anunciar o redesign com antes e depois e explicar o símbolo.',
 roteiro:['Capa: "A Plano tem cara nova"','O que ficou: o nome, a frase e o L de tecido','O que mudou: o rolo agora é vetor, nítido do adesivo à fachada','O L-rolo: o tecido sai do rolo e dobra num "check" de qualidade','Final: "Nosso plano continua o mesmo: dar vida ao seu projeto"'],
 legenda:'A Plano Tecidos está de cara nova! 🌿\nO L continua sendo um rolo de tecido, agora desenhado para aparecer nítido em todo lugar: na etiqueta, no adesivo do pedido e aqui no feed.\nO que não muda é o nosso plano: dar vida ao seu projeto.\nArrasta pro lado e conta pra gente o que achou 👉',
 cta:'Comentar o que achou',tags:'#planotecidos #tecidos #tecidopormetro #costura #novamarca',
 slides:[
  {tpl:'texto',bg:'verde',kicker:'NOVIDADE',title:'A Plano<br>tem cara<br>nova.',sub:'Arrasta pro lado →',sym:true},
  {tpl:'antesdepois'},
  {tpl:'simbolo'},
  {tpl:'texto',bg:'linho',kicker:'O QUE NÃO MUDA',title:'Nosso plano é dar vida ao seu projeto.',sub:'E quando o seu projeto ganha forma, o nosso também se realiza.',logo:true}
 ]},
{id:'s1-02',date:'2026-10-13',hora:'12h',fmt:'motion',pilar:'marca',titulo:'Logo reveal: o rolo desenrola',
 objetivo:'Fixar o símbolo novo em movimento (Reels de 8 s, em loop).',
 roteiro:['0–1 s: o rolo sobe sobre fundo linho','1–2 s: o tecido desenrola e dobra no "check"','2–3 s: as letras P, A, N, O encaixam ao redor do L','3–5 s: TECIDOS abre o espaçamento e entra a frase','5–8 s: assinatura @planotecidos'],
 legenda:'Do rolo ao projeto. 🧵\nEssa é a nova marca da Plano Tecidos em movimento.',
 cta:'Salvar e compartilhar',tags:'#planotecidos #motiondesign #tecidos #costura',motion:'m1-logo'},
{id:'s1-05',date:'2026-10-14',hora:'19h',fmt:'motion',pilar:'marca',titulo:'Do sonho ao vestido',
 objetivo:'Filme principal da nova marca (56 s, com trilha): da busca pelo vestido à avaliação 5 estrelas na loja.',
 roteiro:['Ela precisa de um vestido e nenhum do provador serve','Tem a ideia de criar o próprio e rabisca o modelo','Busca o tecido e encontra a tricoline listrada rosa da Plano na Shopee','Escolhe 2,5 m e finaliza a compra','O pacote chega rápido, com o adesivo da Plano','No ateliê, a costureira transforma o tecido no vestido','Ela veste, gira e se sente confortável','Tecido certo, entrega rápida, qualidade','Avalia a loja com 5 estrelas e um comentário','Final: logo, assinatura e shopee.com.br/planotecidos'],
 legenda:'Todo vestido começa com um plano. E um pano. 💚\nEla não achou o vestido que queria. Então escolheu o tecido, levou ao ateliê e vestiu exatamente o que imaginou.\nTricoline listrada rosa disponível por metro na nossa loja da Shopee (link na bio).',
 cta:'Comprar na Shopee',tags:'#planotecidos #costura #vestidosobmedida #tricoline #tecidopormetro',motion:'m5-historia'},
{id:'s1-03',date:'2026-10-15',hora:'19h',fmt:'estatico',pilar:'marca',titulo:'Manifesto',
 objetivo:'Dar voz à marca com a frase da bio.',
 roteiro:['Frase da bio em destaque sobre linho, com o logotipo'],
 legenda:'Todo projeto começa com um plano e um pano. 💚\nSeja uma roupa, uma fantasia ou uma mesa posta, a gente separa o tecido certo, corta na medida e envia com carinho.',
 cta:'Chamar no WhatsApp',tags:'#planotecidos #costuracriativa #feitoamao #tecidos',
 art:{tpl:'texto',bg:'linho',kicker:'MANIFESTO',title:'Todo projeto começa com um <em>plano</em> e um <em>pano</em>.',logo:true}},
{id:'s1-04',date:'2026-10-17',hora:'11h',fmt:'carrossel',pilar:'produto',titulo:'Tricolines listradas',
 objetivo:'Mostrar produto real com nome, uso e chamada.',
 roteiro:['Capa: foto da tricoline rosa com fita métrica','Foto da azul listrada','Ideias de uso: camisa, vestido, pijama, necessaire','Chamada: peça a sua por metro'],
 legenda:'Listras que combinam com tudo: tricolines rosa e azul. 🩷💙\nBoas para camisa, vestido, pijama infantil e necessaire.\nPeça por metro no WhatsApp ou na Shopee (link na bio).',
 cta:'Comprar na Shopee',tags:'#tricoline #tricolinelistrada #tecidopormetro #costura #planotecidos',
 slides:[
  {tpl:'foto',img:'tricoline-rosa-listrada.jpg',kicker:'TRICOLINE LISTRADA',title:'Rosa',sub:'Leve, fresca e fácil de costurar.'},
  {tpl:'foto',img:'tricoline-azul-listrada.jpg',kicker:'TRICOLINE LISTRADA',title:'Azul',sub:'A listra clássica que vira camisa, vestido ou pijama.'},
  {tpl:'lista',bg:'linho',kicker:'IDEIAS DE USO',title:'O que fazer com tricoline',items:['Camisa e camisão','Vestido e saia','Pijama infantil','Necessaire e bolsinhas']}
 ]},
/* ---------------- SEMANA 2 ---------------- */
{id:'s2-01',date:'2026-10-19',hora:'19h',fmt:'carrossel',pilar:'educa',titulo:'Tecido plano x malha',
 objetivo:'Conteúdo salvável que explica o próprio nome da marca.',
 roteiro:['Capa: "Tecido plano ou malha?"','Tecido plano: fios que se cruzam (trama e urdume)','Malha: um fio que forma laçadas','Como reconhecer: estica? desfia?','Na Plano você encontra tecidos planos para cada projeto'],
 legenda:'Você sabe por que a gente se chama Plano? 🤔\nTecido plano é aquele feito de fios que se cruzam, como tricoline, linho, sarja e cetim. Malha é feita de laçadas, como a da camiseta.\nSalva esse post pra consultar na próxima compra!',
 cta:'Salvar o post',tags:'#tecidoplano #dicasdecostura #costuraparainiciantes #tecidos #planotecidos',
 slides:[
  {tpl:'texto',bg:'musgo',kicker:'DICA DE COSTURA',title:'Tecido <em>plano</em> ou malha?',sub:'Entenda de vez (e o porquê do nosso nome).',sym:true},
  {tpl:'compare'},
  {tpl:'lista',bg:'linho',kicker:'COMO RECONHECER',title:'Faça o teste',items:['Puxou e esticou muito? Malha.','Puxou e quase não cedeu? Plano.','Fios cruzados em xadrez miúdo? Plano.','Laçadas em "V"? Malha.']}
 ]},
{id:'s2-02',date:'2026-10-21',hora:'12h',fmt:'motion',pilar:'produto',titulo:'Chegou na Plano',
 objetivo:'Template de novidades da semana (Reels de 12 s, reutilizável).',
 roteiro:['Título "Chegou na Plano"','4 tecidos entram em sequência com nome (2 s cada)','Final: compre por metro, WhatsApp e Shopee'],
 legenda:'Novidades da semana na Plano! ✨\nQual desses vai para o seu próximo projeto? Comenta o número 👇',
 cta:'Comentar o número',tags:'#novidades #tecidos #tecidopormetro #planotecidos',motion:'m2-novidades'},
{id:'s2-03',date:'2026-10-23',hora:'19h',fmt:'estatico',pilar:'produto',titulo:'Cristal furta-cor',
 objetivo:'Destacar o tecido de festa/fantasia antes do Halloween.',
 roteiro:['Foto do cristal furta-cor','Título e usos: fantasia, saia de tule, decoração de festa'],
 legenda:'Ele muda de cor conforme a luz. ✨\nO cristal furta-cor é o queridinho para fantasias, saias de festa e decoração.\nPeça o seu por metro: link na bio.',
 cta:'Chamar no WhatsApp',tags:'#furtacor #tecidodefesta #fantasia #tecidos #planotecidos',
 art:{tpl:'foto',img:'cristal-furtacor.jpg',kicker:'CRISTAL FURTA-COR',title:'Muda de cor com a luz.',sub:'Fantasias, saias de festa e decoração.'}},
{id:'s2-04',date:'2026-10-25',hora:'11h',fmt:'estatico',pilar:'prova',titulo:'Nota 5 na Shopee',
 objetivo:'Redesenhar o post de prova social no novo sistema visual.',
 roteiro:['Nota 5 e vendedor indicado','Três selos: atendimento, qualidade, envio'],
 legenda:'Nota 5 e vendedor indicado na Shopee. ⭐\nObrigada a cada cliente que confiou no nosso plano!\nEncontre a gente em shopee.com.br/planotecidos',
 cta:'Visitar a loja na Shopee',tags:'#shopee #lojadetecidos #tecidos #planotecidos',
 art:{tpl:'prova'}},
/* ---------------- SEMANA 3 ---------------- */
{id:'s3-01',date:'2026-10-26',hora:'19h',fmt:'carrossel',pilar:'educa',titulo:'5 tecidos para fantasia',
 objetivo:'Conteúdo sazonal e salvável para o Halloween (31/10).',
 roteiro:['Capa: "5 tecidos para a fantasia de Halloween"','Organza','Cristal furta-cor','Tule com flocos','Cetim','Cores lisas (forro e peças base)'],
 legenda:'Fantasia boa começa no tecido certo. 🎃\n5 escolhas para o Halloween, da capa de bruxa à fada.\nMarca quem vai costurar a fantasia esse ano!',
 cta:'Marcar um amigo',tags:'#halloween #fantasia #fantasiadehalloween #costura #planotecidos',
 slides:[
  {tpl:'texto',bg:'grafite',kicker:'HALLOWEEN · 31/10',title:'5 tecidos para a sua <em>fantasia</em>',sub:'Arrasta e escolhe o seu →',sym:true},
  {tpl:'foto',img:'organza-rosa.jpg',kicker:'01 · ORGANZA',title:'Leveza para asas e capas',sub:'Transparente e com brilho suave.'},
  {tpl:'foto',img:'tule-flocos.jpg',kicker:'02 · TULE COM FLOCOS',title:'Princesa do gelo',sub:'Saia volumosa e capa com brilho.'},
  {tpl:'foto',img:'cetim-azul.jpg',kicker:'03 · CETIM',title:'Brilho de vestido de gala',sub:'Corpete, capa e laços.'},
  {tpl:'foto',img:'cristal-furtacor.jpg',kicker:'04 · CRISTAL FURTA-COR',title:'Sereia e unicórnio',sub:'Muda de cor conforme a luz.'},
  {tpl:'foto',img:'rolos-cores.jpg',kicker:'05 · CORES LISAS',title:'A base da fantasia',sub:'Forro, macacão e acabamentos.'}
 ]},
{id:'s3-02',date:'2026-10-28',hora:'12h',fmt:'reels',pilar:'bastidor',titulo:'Do rolo ao pedido',
 objetivo:'Mostrar o cuidado: medir, cortar, dobrar e embalar (filmado no celular).',
 roteiro:['Plano detalhe: o rolo girando na bancada (2 s)','Fita métrica medindo (2 s)','Tesoura cortando, com o som do corte (3 s)','Dobra e adesivo novo da marca (3 s)','Pacote pronto + texto "Seu projeto a caminho" (2 s)'],
 legenda:'Do rolo até a sua casa, com carinho em cada etapa. 📦\nÉ assim que o seu pedido sai da Plano.',
 cta:'Seguir o perfil',tags:'#bastidores #pequenonegocio #tecidos #planotecidos',
 art:{tpl:'capa',img:'rolos-diagonal.jpg',title:'Do rolo<br>ao pedido',kicker:'BASTIDORES'}},
{id:'s3-03',date:'2026-10-30',hora:'19h',fmt:'estatico',pilar:'oferta',titulo:'Halloween: última chamada',
 objetivo:'Urgência para quem ainda vai costurar a fantasia.',
 roteiro:['Texto de urgência + tecidos de fantasia','Chamada para o WhatsApp'],
 legenda:'Ainda dá tempo! 🎃\nChama no WhatsApp que a gente separa o tecido da sua fantasia hoje mesmo.',
 cta:'Chamar no WhatsApp',tags:'#halloween #fantasia #tecidos #planotecidos',
 art:{tpl:'texto',bg:'grafite',kicker:'HALLOWEEN',title:'Ainda dá tempo de costurar a <em>fantasia</em>.',sub:WA,sym:true}},
{id:'s3-04',date:'2026-11-01',hora:'11h',fmt:'stories',pilar:'educa',titulo:'Enquete: qual o seu próximo projeto?',
 objetivo:'Ouvir o público para guiar o catálogo.',
 roteiro:['Story 1: "Qual o seu próximo projeto?" enquete (roupa / decoração)','Story 2: caixa de perguntas "Que tecido você procura?"','Story 3: resultado + tecidos sugeridos'],
 legenda:'(Stories) Enquete e caixa de perguntas.',cta:'Responder a enquete',tags:'',
 art:{tpl:'story',title:'Qual o seu próximo projeto?',opts:['Roupa','Decoração']}},
/* ---------------- SEMANA 4 ---------------- */
{id:'s4-01',date:'2026-11-02',hora:'19h',fmt:'motion',pilar:'educa',titulo:'Como comprar em 3 passos',
 objetivo:'Tirar a dúvida mais comum: como comprar por metro na Shopee (Reels de 14 s).',
 roteiro:['Passo 1: escolha o tecido na loja Plano Tecidos da Shopee','Passo 2: selecione a metragem','Passo 3: finalize a compra na Shopee e receba em casa','Final: shopee.com.br/planotecidos'],
 legenda:'Comprar tecido por metro é simples assim. ✂️\n1. Escolha o tecido na nossa loja da Shopee\n2. Selecione a metragem\n3. Finalize a compra e receba em casa\nLink na bio: shopee.com.br/planotecidos',
 cta:'Comprar na Shopee',tags:'#tecidopormetro #comocomprar #tecidos #planotecidos',motion:'m3-comprar'},
{id:'s4-02',date:'2026-11-04',hora:'19h',fmt:'carrossel',pilar:'educa',titulo:'Quantos metros eu compro?',
 objetivo:'Conteúdo útil para salvar e reduzir dúvidas no atendimento.',
 roteiro:['Capa: "Quantos metros eu compro?"','Regra geral: meça a peça + margem de costura','Considere a largura do tecido (ex.: 1,40 m ou 1,50 m)','Estampa listrada pede um pouco a mais para casar as listras','Na dúvida, mande o molde no WhatsApp'],
 legenda:'Antes de comprar, faça essa conta. 📏\nSalva para usar no próximo projeto e, na dúvida, manda o molde no WhatsApp que a gente ajuda.',
 cta:'Salvar o post',tags:'#dicasdecostura #modelagem #tecidopormetro #planotecidos',
 slides:[
  {tpl:'texto',bg:'verde',kicker:'DICA DE COSTURA',title:'Quantos metros eu compro?',sub:'Arrasta para fazer a conta →',sym:true},
  {tpl:'lista',bg:'linho',kicker:'A CONTA',title:'Antes de pedir',items:['Meça o comprimento das peças do molde','Some a margem de costura e a barra','Confira a largura do tecido','Listras e xadrez pedem um pouco a mais']},
  {tpl:'texto',bg:'musgo',kicker:'NA DÚVIDA',title:'Manda o molde que a gente calcula com você.',sub:WA}
 ]},
{id:'s4-03',date:'2026-11-06',hora:'19h',fmt:'estatico',pilar:'produto',titulo:'Paleta de cetins',
 objetivo:'Mostrar a variedade de cores.',
 roteiro:['Foto dos rolos de cetim em várias cores','Chamada para escolher a cor'],
 legenda:'Qual cor é a sua? 🌈\nCetins em várias cores para festa, laço, forro e decoração.',
 cta:'Comentar a cor favorita',tags:'#cetim #tecidodefesta #cores #planotecidos',
 art:{tpl:'foto',img:'rolos-verticais.jpg',kicker:'CETIM',title:'Qual cor é a sua?',sub:'Festa, laço, forro e decoração.'}},
{id:'s4-04',date:'2026-11-08',hora:'11h',fmt:'reels',pilar:'bastidor',titulo:'O som do tecido (ASMR)',
 objetivo:'Formato de alto alcance: sons de corte, dobra e tecido.',
 roteiro:['Sem fala, só o som ambiente','Mão passando no tecido (cetim, linho, tule)','Tesoura cortando em close','Rolo desenrolando na bancada','Final: logo em linho e @planotecidos'],
 legenda:'Aumenta o volume. 🔊✂️',cta:'Compartilhar',tags:'#asmr #costura #tecidos #planotecidos',
 art:{tpl:'capa',img:'algodao-cru.jpg',title:'Aumenta<br>o volume',kicker:'ASMR'}},
/* ---------------- SEMANA 5 ---------------- */
{id:'s5-01',date:'2026-11-09',hora:'19h',fmt:'carrossel',pilar:'produto',titulo:'Mesa posta de fim de ano',
 objetivo:'Inspirar projetos de decoração com tecidos naturais.',
 roteiro:['Capa: mesa posta começa no tecido','Algodão cru: toalha e guardanapos','Linho rosa: caminho de mesa','Dica de acabamento: barra com ponto invisível'],
 legenda:'A mesa de fim de ano começa no tecido. 🍽️\nAlgodão cru e linho para toalha, caminho de mesa e guardanapos feitos por você.',
 cta:'Salvar a inspiração',tags:'#mesaposta #decoracao #natal #linho #planotecidos',
 slides:[
  {tpl:'foto',img:'algodao-cru.jpg',kicker:'MESA POSTA',title:'Começa no tecido',sub:'Toalha, caminho e guardanapos feitos por você.'},
  {tpl:'foto',img:'linho-rosa.jpg',kicker:'LINHO',title:'Caminho de mesa',sub:'Textura natural que valoriza a louça.'},
  {tpl:'lista',bg:'linho',kicker:'MEDIDAS DE REFERÊNCIA',title:'Para uma mesa de 6 lugares',items:['Toalha: mesa + 25 cm de cada lado','Caminho: 35 a 40 cm de largura','Guardanapo: 40 × 40 cm','Confirme as medidas da sua mesa']}
 ]},
{id:'s5-02',date:'2026-11-11',hora:'19h',fmt:'estatico',pilar:'produto',titulo:'Tule com flocos',
 objetivo:'Antecipar a demanda de Natal.',
 roteiro:['Foto do tule com flocos de neve','Título sazonal'],
 legenda:'O tecido que já tem cara de Natal. ❄️\nTule com flocos para saias, decoração de árvore e fantasias de princesa do gelo.',
 cta:'Chamar no WhatsApp',tags:'#natal #tule #decoracaodenatal #planotecidos',
 art:{tpl:'foto',img:'tule-flocos.jpg',kicker:'TULE COM FLOCOS',title:'Já tem cara de Natal.',sub:'Saias, decoração e fantasias.'}},
{id:'s5-03',date:'2026-11-13',hora:'12h',fmt:'reels',pilar:'prova',titulo:'Abrindo um pedido',
 objetivo:'Unboxing do ponto de vista do cliente: embalagem e adesivo novo.',
 roteiro:['Pacote chegando na mesa','Abrindo: adesivo Plano em close','Tecido dobrado, mão sentindo a textura','Texto: "Nota 5 na Shopee"','Final: link na bio'],
 legenda:'Abre com a gente? 📦💚\nCada pedido sai dobrado, conferido e com o nosso adesivo.',
 cta:'Visitar a Shopee',tags:'#unboxing #shopee #tecidos #planotecidos',
 art:{tpl:'capa',img:'adesivo-sarja-1.jpg',title:'Abrindo<br>um pedido',kicker:'UNBOXING'}},
{id:'s5-04',date:'2026-11-15',hora:'11h',fmt:'estatico',pilar:'prova',titulo:'#FeitoComPlano',
 objetivo:'Convidar clientes a postar os projetos (gerar conteúdo de cliente).',
 roteiro:['Convite: poste seu projeto com #FeitoComPlano e marque @planotecidos','Repost nos stories'],
 legenda:'Costurou com tecido da Plano? Queremos ver! 🧵\nPoste com #FeitoComPlano e marque @planotecidos. Os projetos vão para os nossos stories.',
 cta:'Postar com #FeitoComPlano',tags:'#FeitoComPlano #costura #planotecidos',
 art:{tpl:'texto',bg:'verde',kicker:'#FEITOCOMPLANO',title:'Costurou com a Plano? <em>Mostra pra gente.</em>',sub:'Marque @planotecidos',sym:true}},
/* ---------------- SEMANA 6 ---------------- */
{id:'s6-01',date:'2026-11-16',hora:'19h',fmt:'estatico',pilar:'oferta',titulo:'Lista de desejos',
 objetivo:'Aquecer a Black Friday: favoritar produtos na Shopee.',
 roteiro:['Chamada para favoritar tecidos na Shopee antes da Black Friday'],
 legenda:'Black Friday chegando! 🖤\nJá favorita os tecidos na nossa loja da Shopee para não perder nada.',
 cta:'Favoritar na Shopee',tags:'#blackfriday #shopee #tecidos #planotecidos',
 art:{tpl:'texto',bg:'grafite',kicker:'BLACK FRIDAY · 27/11',title:'Já monta a sua <em>lista de desejos</em>.',sub:'shopee.com.br/planotecidos',sym:true}},
{id:'s6-02',date:'2026-11-18',hora:'12h',fmt:'motion',pilar:'oferta',titulo:'Contagem Black Friday',
 objetivo:'Lembrete em motion: o tecido desenrola como uma régua até o dia 27.',
 roteiro:['Fita métrica desenrola marcando os dias','"Faltam 9 dias"','Ative o lembrete'],
 legenda:'Faltam 9 dias para a Black Friday da Plano. ⏳\nAtiva o lembrete!',
 cta:'Ativar lembrete',tags:'#blackfriday #tecidos #planotecidos',motion:'m4-blackfriday'},
{id:'s6-03',date:'2026-11-20',hora:'19h',fmt:'carrossel',pilar:'educa',titulo:'Combinações pastel',
 objetivo:'Inspirar combinações com o catálogo real (rosa, azul, verde-sálvia, cru).',
 roteiro:['Capa: 3 combinações pastel','Rosa + cru','Azul + listrado','Sálvia + linho'],
 legenda:'3 combinações pastel para o próximo projeto. 🩷💙💚\nQual é a sua?',
 cta:'Comentar 1, 2 ou 3',tags:'#paletadecores #costura #tecidos #planotecidos',
 slides:[
  {tpl:'paleta'},
  {tpl:'foto',img:'linho-rosa.jpg',kicker:'COMBINAÇÃO 1',title:'Rosa + cru',sub:'Delicado para infantil e decoração.'},
  {tpl:'foto',img:'sarja-azul.jpg',kicker:'COMBINAÇÃO 2',title:'Azul + listra',sub:'Fresco para o verão.'}
 ]},
{id:'s6-04',date:'2026-11-22',hora:'11h',fmt:'estatico',pilar:'oferta',titulo:'Ative o lembrete',
 objetivo:'Último aquecimento antes da semana da Black Friday.',
 roteiro:['Chamada final + contatos'],
 legenda:'Semana que vem tem Black Friday na Plano. 🖤\nAtive o lembrete e chame no WhatsApp para reservar o seu tecido.',
 cta:'Ativar lembrete',tags:'#blackfriday #tecidos #planotecidos',
 art:{tpl:'texto',bg:'musgo',kicker:'BLACK FRIDAY',title:'Semana que vem tem <em>Black Friday</em> na Plano.',sub:WA,logo:true}}
];
